name: fdp-info
favicon: null
layout_spectrum: 0.24884130177088082
typography_spectrum: 0.16334461700171232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5999119861517102
  lightness: 0.005309326807036996
  saturation: 0.9191512474790215
  rhythmicContrast: 0.5138837173581123
purpose: []
